sonar.projectKey=wmoreno38_L-NEA1.5
sonar.organization=wmoreno38

# Exclude the base64 Excel template from analysis
sonar.exclusions=**/template.js,**/node_modules/**,**/dist/**

# Source directory
sonar.sources=linea15-demo/src

# Exclude test and config files
sonar.coverage.exclusions=**/template.js
